/**
 * When each ayah is recited inside its ruku's recording, in seconds from the start of the
 * file, keyed "<para>|<rukuInPara>" exactly as verses.js is.
 *
 * Generated by scripts/align-ayat.py + scripts/build-timings.js — do not edit by hand for
 * anything a re-run would overwrite. Only rukus that have been aligned appear here.
 *
 * `ayahs` holds [ayah number, second] pairs, in recitation order. Ayat the aligner could
 * not place with confidence are absent rather than guessed at: the app keeps the previous
 * ayah lit across the gap, which is right anyway — the shaykh is still explaining it.
 *
 * `trim` is where the lecture's own content begins and ends, past the opening branding and
 * before the closing announcements. Offsets only; the audio files are untouched.
 */
const QURAN_TIMINGS = {
  "1|R1": {
    trim: { start: 21.84, end: 153.98 },
    ayahs: [[2, 30.14], [3, 42.02], [4, 59.71], [5, 90.02], [6, 101.59], [7, 121.08]]
  },
  "1|R2": {
    trim: { start: 0, end: 352.8 },
    ayahs: [[8, 14.8], [9, 36.82], [10, 52.9], [11, 83.6], [12, 101.92], [13, 124.08], [14, 144.74], [15, 183.19], [16, 199.9], [17, 224.89], [18, 256.48], [19, 268.14], [20, 304.42]]
  },
  "1|R3": {
    trim: { start: 103.66, end: 428.4 },
    ayahs: [[21, 104.23], [22, 126.98], [23, 164.64], [24, 198.24], [25, 221.32], [26, 280.2], [27, 339.72], [28, 368.32], [29, 396.92]]
  },
  "1|R4": {
    trim: { start: 27.12, end: 450.36 },
    ayahs: [[30, 36.28], [31, 99.38], [32, 131.84], [33, 154.71], [34, 204.53], [35, 228.26], [36, 267.06], [37, 305], [38, 324.58], [39, 358.39]]
  },
  "1|R5": {
    trim: { start: 82.79, end: 315.46 },
    ayahs: [[40, 83.19], [41, 119.53], [42, 151.8], [43, 177.83], [44, 188.98], [45, 203.66], [46, 226.2]]
  },
  "1|R6": {
    trim: { start: 167.72, end: 604.88 },
    ayahs: [[47, 168.12], [48, 183.38], [49, 222.38], [50, 254.66], [51, 271.02], [52, 286.12], [53, 295.12], [54, 306.46], [55, 348.89], [56, 368.46], [57, 378.53], [58, 406.68], [59, 438.12]]
  },
  "1|R7": {
    trim: { start: 75.76, end: 314.32 },
    ayahs: [[60, 79.06], [61, 141.74]]
  },
  "1|R8": {
    trim: { start: 51.92, end: 364.72 },
    ayahs: [[62, 53.16], [63, 93.08], [64, 120.81], [65, 139.02], [66, 165.28], [67, 177.9], [68, 206.72], [69, 241.44], [70, 266.68], [71, 297.76]]
  },
  "1|R9": {
    trim: { start: 117.3, end: 482.46 },
    ayahs: [[72, 123.08], [73, 138.87], [74, 161.2], [75, 231.5], [76, 262.26], [77, 309.47], [78, 318], [79, 333.08], [80, 364.22], [81, 411.72], [82, 418.72]]
  },
  "1|R10": {
    trim: { start: 16.44, end: 230.86 },
    ayahs: [[83, 19.14], [84, 75.08], [85, 107.16], [86, 198.24]]
  },
  "1|R11": {
    trim: { start: 20.68, end: 550.46 },
    ayahs: [[87, 24.1], [88, 95.1], [89, 111.95], [90, 152.58], [91, 197.68], [92, 232.17], [93, 252.76], [94, 303.4], [95, 320.79], [96, 334.14]]
  },
  "1|R12": {
    trim: { start: 13.72, end: 482.18 },
    ayahs: [[97, 21.62], [98, 52.7], [99, 66.41], [100, 87.99], [101, 99.21], [102, 143.72], [103, 345.9]]
  },
  "1|R13": {
    trim: { start: 7.54, end: 320.68 },
    ayahs: [[104, 8.86], [105, 45.08], [106, 80.9], [107, 125.19], [108, 138.84], [109, 167.46], [110, 212.9], [111, 235.54], [112, 276.42]]
  },
  "1|R14": {
    trim: { start: 44.64, end: 475.7 },
    ayahs: [[113, 47.91], [114, 152.92], [115, 221.94], [116, 237.27], [117, 252.32], [118, 272.32], [119, 324.02], [120, 337.99], [121, 391.73]]
  },
  "1|R15": {
    trim: { start: 48.14, end: 374 },
    ayahs: [[122, 57.51], [123, 84.76], [124, 125.26], [125, 169.8], [126, 223.74], [127, 267.94], [128, 290.98], [129, 315.28]]
  },
  "1|R16": {
    trim: { start: 50.74, end: 514.46 },
    ayahs: [[130, 60.07], [131, 109.62], [132, 128.38], [133, 168.46], [134, 212.92], [135, 242.64], [136, 273.76], [137, 318.32], [138, 374.38], [139, 385.2], [140, 420.7], [141, 454.2]]
  }
};

if (typeof module !== "undefined" && module.exports) module.exports = QURAN_TIMINGS;
