/**
 * Build timings.js — when each ayah is recited, and where the lecture's content starts and
 * stops, for the rukus scripts/align-ayat.py has been run over.
 *
 * Run:  node scripts/build-timings.js                 (fold in everything aligned so far)
 *       node scripts/build-timings.js --prune         (also drop keys data.js no longer has)
 *       node scripts/build-timings.js --min-placed 4  (skip rukus with fewer ayat placed)
 *
 * Existing entries are kept, so paras can be aligned a few at a time — the same way
 * build-verses.js grows verses.js. The alignments themselves live in .cache/align/rukus/,
 * which is gitignored: this file is the committed artefact, and re-running the aligner is
 * what regenerates it.
 *
 * A ruku with no entry here is not broken, it is just not aligned yet. The panel falls back
 * to highlighting nothing and the player to playing the whole file, which is what it did
 * before any of this existed.
 */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const rootDir = path.join(__dirname, "..");
const alignDir = path.join(rootDir, ".cache", "align", "rukus");
const outPath = path.join(rootDir, "timings.js");

/** data.js / timings.js declare their payload with `const`, so read the script's completion value. */
function evalDataFile(filePath, globalName) {
  const sandbox = {};
  vm.createContext(sandbox);
  return vm.runInContext(fs.readFileSync(filePath, "utf8") + "\n" + globalName + ";", sandbox);
}

function loadExisting() {
  if (!fs.existsSync(outPath)) return {};
  return evalDataFile(outPath, "QURAN_TIMINGS") || {};
}

function serialize(timings) {
  const lines = [
    "/**",
    " * When each ayah is recited inside its ruku's recording, in seconds from the start of the",
    " * file, keyed \"<para>|<rukuInPara>\" exactly as verses.js is.",
    " *",
    " * Generated by scripts/align-ayat.py + scripts/build-timings.js — do not edit by hand for",
    " * anything a re-run would overwrite. Only rukus that have been aligned appear here.",
    " *",
    " * `ayahs` holds [ayah number, second] pairs, in recitation order. Ayat the aligner could",
    " * not place with confidence are absent rather than guessed at: the app keeps the previous",
    " * ayah lit across the gap, which is right anyway — the shaykh is still explaining it.",
    " *",
    " * `trim` is where the lecture's own content begins and ends, past the opening branding and",
    " * before the closing announcements. Offsets only; the audio files are untouched.",
    " */",
    "const QURAN_TIMINGS = {",
  ];
  const keys = Object.keys(timings).sort((a, b) => {
    const [pa, ra] = a.split("|");
    const [pb, rb] = b.split("|");
    return Number(pa) - Number(pb) || Number(ra.slice(1)) - Number(rb.slice(1));
  });
  keys.forEach((key, i) => {
    const t = timings[key];
    const pairs = t.ayahs.map((a) => `[${a[0]}, ${a[1]}]`).join(", ");
    lines.push(`  ${JSON.stringify(key)}: {`);
    lines.push(`    trim: { start: ${t.trim.start}, end: ${t.trim.end} },`);
    lines.push(`    ayahs: [${pairs}]`);
    lines.push(`  }${i === keys.length - 1 ? "" : ","}`);
  });
  lines.push("};");
  lines.push("");
  lines.push("if (typeof module !== \"undefined\" && module.exports) module.exports = QURAN_TIMINGS;");
  lines.push("");
  return lines.join("\n");
}

function main() {
  const args = process.argv.slice(2);
  const prune = args.includes("--prune");
  const minIdx = args.indexOf("--min-placed");
  const minPlaced = minIdx === -1 ? 2 : Number(args[minIdx + 1]);
  // NaN here would be worse than a wrong number: `length < NaN` is false for every ruku, so a
  // typo or a trailing --min-placed would quietly turn the filter off and write one-ayah junk
  // into timings.js as though it had passed.
  if (!Number.isFinite(minPlaced) || minPlaced < 0) {
    console.error(`--min-placed needs a non-negative number, got ${JSON.stringify(args[minIdx + 1])}`);
    return 1;
  }

  if (!fs.existsSync(alignDir)) {
    console.error(`no alignments in ${path.relative(rootDir, alignDir)} — run scripts/align-ayat.sh first`);
    return 1;
  }
  const live = new Set(
    evalDataFile(path.join(rootDir, "data.js"), "QURAN_DATA").map((r) => `${r.para}|${r.rukuInPara}`)
  );

  const timings = loadExisting();
  let added = 0;
  let thin = 0;
  for (const file of fs.readdirSync(alignDir).filter((f) => f.endsWith(".json"))) {
    const res = JSON.parse(fs.readFileSync(path.join(alignDir, file), "utf8"));
    // No trim means nothing was placed at all, so there is nothing to say about this ruku.
    // The threshold cannot exceed what the ruku actually contains: An-Nisa 23 is a ruku of one
    // ayah, and "fewer than two placed" dropped it while it was in fact complete.
    const floor = Math.min(minPlaced, res.of || minPlaced);
    if (!res.trim || !res.ayahs || res.ayahs.length < floor) {
      thin += 1;
      continue;
    }
    timings[res.key] = {
      trim: res.trim,
      ayahs: res.ayahs.map((a) => [a.n, a.t]),
    };
    added += 1;
  }

  let pruned = 0;
  if (prune) {
    for (const key of Object.keys(timings)) {
      if (!live.has(key)) {
        delete timings[key];
        pruned += 1;
      }
    }
  }

  fs.writeFileSync(outPath, serialize(timings), "utf8");
  const total = Object.keys(timings).length;
  console.log(`timings.js: ${total} ruku(s)  (+${added} this run, ${thin} too thin to use` +
    `${prune ? `, ${pruned} pruned` : ""})`);
  return 0;
}

process.exit(main());
