/**
 * Swap the ayah text in verses.js for the Indo-Pak (Nastaleeq) script, in place.
 *
 * Run:  node scripts/indopak-verses.js
 *
 * Source: api.quran.com, `text_indopak_nastaleeq` — the text drawn for the KFGQPC IndoPak
 * Nastaleeq font in asset/fonts. Its trailing ayah-number glyph is dropped, since the UI
 * draws its own marker. Some ligatures (أُنثَىٰ, وَٱلَّٰٓـِٔى …) are private-use glyphs of that
 * font, so the text only reads right in it. Keys, numbering and basmala flags are untouched.
 */
const fs = require("fs");
const path = require("path");

const outPath = path.join(__dirname, "..", "verses.js");
const URL = "https://api.quran.com/api/v4/quran/verses/indopak_nastaleeq";

async function main() {
  const res = await fetch(URL);
  if (!res.ok) throw new Error("HTTP " + res.status + " for " + URL);
  const text = {};
  (await res.json()).verses.forEach((v) => {
    text[v.verse_key] = v.text_indopak_nastaleeq.replace(/\s*[-]+$/, "").trim();
  });

  let surah = 0;
  let swapped = 0;
  const lines = fs.readFileSync(outPath, "utf8").split("\n").map((line) => {
    const s = line.match(/^\s*surahNumber: (\d+),/);
    if (s) surah = Number(s[1]);
    if (/^ \* (Uthmani|Generated by)/.test(line)) {
      return line.startsWith(" * Uthmani")
        ? " * Indo-Pak (Nastaleeq) Arabic ayah text, keyed by \"<para>|<rukuInPara>\" (e.g. \"10|R1\")."
        : " * Built by scripts/build-verses.js, then swapped to Indo-Pak by scripts/indopak-verses.js.";
    }
    return line.replace(/^(\s*\{ n: (\d+), text: ")(.*)(" \},?)$/, (all, head, n, old, tail) => {
      const t = text[surah + ":" + n];
      if (!t) throw new Error("No Indo-Pak text for " + surah + ":" + n);
      swapped++;
      return head + t.replace(/\\/g, "\\\\").replace(/"/g, "\\\"") + tail;
    });
  });
  fs.writeFileSync(outPath, lines.join("\n"));
  console.log("Swapped " + swapped + " ayat to Indo-Pak.");
}

main().catch((e) => { console.error(e); process.exit(1); });
