/**
 * Swap the ayah text in verses.js for the Indo-Pak (Nastaleeq) script, in place.
 *
 * Run:  node scripts/indopak-verses.js path/to/indopak-nastaleeq.json
 *
 * Source: QUL "Indopak Nastaleeq script - Word by Word" (qul.tarteel.ai/resources/quran-script/59),
 * a JSON keyed "surah:ayah:word". Its words line up with quran.com's word lists, so tapped
 * words find their meanings. The text is written for the KFGQPC IndoPak Nastaleeq font in
 * asset/fonts: some words and signs are that font's private-use glyphs, kept as they are.
 * Each ayah ends in a token holding its closing pause marks and the font's numbered
 * ornament. The plain ornament (U+F500..U+F61D, and U+F61E, the unnumbered ring after the
 * Fatiha's basmala) is dropped: the app draws it from the ayah number, since the Fatiha's
 * ornaments count from the basmala's end and ours from the basmala. The ornaments with a
 * sajdah or stacked pause sign built in stay, and the app shows them in its place.
 * Keys, numbering and basmala flags are untouched.
 */
const fs = require("fs");
const path = require("path");

const outPath = path.join(__dirname, "..", "verses.js");
const src = process.argv[2];
if (!src) {
  console.error("Usage: node scripts/indopak-verses.js path/to/indopak-nastaleeq.json");
  process.exit(1);
}

/**
 * A word whose space splits letters, not a word and its pause mark (وَّاَنْ لَّوِ in 72:16,
 * اِلْ یَاسِیْنَ in 37:130), is one word in quran.com's lists too. The app splits ayat on
 * spaces, so its space becomes a zero-width non-joiner and it stays one tappable word.
 */
function oneWord(w) {
  return w.replace(/(\S*[\u0621-\u064A\u0671-\u06D3]\S*) (?=\S*[\u0621-\u064A\u0671-\u06D3])/g, "$1\u200C");
}

function ayahText(words) {
  return words.map(oneWord).join(" ")
    .replace("\uF693\u06DF", "\u06DF\uF693") // 22:77's ornament comes before its closing mark
    .replace(/[\uF500-\uF61E]/g, "")
    .trim();
}

const byAyah = {};
Object.values(JSON.parse(fs.readFileSync(src, "utf8"))).forEach((w) => {
  (byAyah[w.surah + ":" + w.ayah] = byAyah[w.surah + ":" + w.ayah] || [])[w.word - 1] = w.text;
});

let surah = 0;
let swapped = 0;
const lines = fs.readFileSync(outPath, "utf8").split("\n").map((line) => {
  const s = line.match(/^\s*surahNumber: (\d+),/);
  if (s) surah = Number(s[1]);
  if (/^ \* (Uthmani|Generated by)/.test(line)) {
    return line.startsWith(" * Uthmani")
      ? " * Indo-Pak (Nastaleeq) Arabic ayah text, keyed by \"<para>|<rukuInPara>\" (e.g. \"10|R1\")."
      : " * Built by scripts/build-verses.js, then swapped to Indo-Pak by scripts/indopak-verses.js.";
  }
  return line.replace(/^(\s*\{ n: (\d+), text: ")(.*)(" \},?)$/, (all, head, n, old, tail) => {
    const words = byAyah[surah + ":" + n];
    if (!words || words.includes(undefined)) throw new Error("No complete QUL text for " + surah + ":" + n);
    swapped++;
    return head + ayahText(words).replace(/\\/g, "\\\\").replace(/"/g, "\\\"") + tail;
  });
});
fs.writeFileSync(outPath, lines.join("\n"));
console.log("Swapped " + swapped + " ayat to Indo-Pak.");
